name: galsa_trial2
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  flutter_bloc: ^8.1.4
  dio: ^5.5.0+1
  conditional_builder_null_safety: ^0.0.6
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  webview_flutter: ^4.9.0
  fluttertoast: ^8.2.6
  flutter_advanced_segment: ^3.0.2
  intl: ^0.19.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  retrofit: ^4.2.0
  retrofit_generator: ^8.2.0
  pretty_dio_logger: ^1.4.0
  easy_localization: ^3.0.7
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sign_in_button: ^3.2.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6 # For code generation with retrofit_generator, json_serializable

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

# Ensure custom fonts are correctly added
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
